export const sample_food:any[]=[
    {
        id:'1',
        price: 90,
        name: 'pizza Pepperoni',
        favorite:false,
        star: 4.8,
        tag:['FastFood','Pizza','Lunch'],
        imageUrl: 'assets/food1.jpeg',
        cookTime: '40-50',
        origins:['italy'],
      },
      {
        id:'2',
        price: 90,
        name: 'Meatball',
        favorite:true,
        star: 4.8,
        tag:['FastFood','Pizza','Lunch'],
        imageUrl: 'assets/food2.jpeg',
        cookTime: '40-50',
        origins:['china','middle-east'],
      },
      {
        id:'3',
        price: 90,
        name: 'Hamburger',
        favorite:false,
        star: 4.8,
        tag:['FastFood','Hamburger'],
        imageUrl: 'assets/food3.jpeg',
        cookTime: '40-50',
        origins:['italy'],
      },
      {
        id:'4',
        price: 90,
        name: 'Fried Potatoes',
        favorite:true,
        star: 4.8,
        tag:['FastFood','Fried'],
        imageUrl: 'assets/food4.jpeg',
        cookTime: '40-50',
        origins:['belgium','france'],
      },
      {
        id:'5',
        price: 50,
        name: 'Chicken Soup',
        favorite:false,
        star: 4.8,
        tag:['meat'],
        imageUrl: 'assets/food5.jpeg',
        cookTime: '40-50',
        origins:['india','asia'],
      },
      {
        id:'6',
        price: 90,
        name: 'vegetable pizza',
        favorite:false,
        star: 4.8,
        tag:['Pizza','FastFood','Lunch'],
        imageUrl: 'assets/food6.jpeg',
        cookTime: '40-50',
        origins:['italy'],
      },
      {
        id:'7',
        price: 40,
        name: 'vegetable spicy pizza',
        favorite:true,
        star: 4.8,
        tag:['Pizza','FastFood','Lunch'],
        imageUrl: 'assets/food6.jpeg',
        cookTime: '40-50',
        origins:['indian'],
      },
      {
        id:'8',
        price: 60,
        name: 'vegetable burger',
        favorite:true,
        star: 4.8,
        tag:['Pizza','FastFood','Lunch'],
        imageUrl: 'assets/food6.jpeg',
        cookTime: '40-50',
        origins:['indian'],
      },
      {
        id:'9',
        price: 60,
        name: 'Lunch',
        favorite:true,
        star: 4.8,
        tag:['Pizza','FastFood','Lunch'],
        imageUrl: 'assets/food6.jpeg',
        cookTime: '40-50',
        origins:['indian'],
      }
]

export const sample_tags:any[]=[
  { name: 'All', count:14 },
      { name: 'meat', count:4 },
      { name: 'FastFood', count:2 },
      { name: 'Hamburger', count:3},
      { name: 'Lunch', count:2},
]

export const sample_users:any[]=[
      {
        name: "Ashish Mishra",
        email: "ashish@gmail.com",
        password: "Chaitali123",
        address: "Pune",
        isAdmin: true,
       },

       {
        name: "Avish Mishra",
        email: "avish@gmail.com",
        password: "Avish@123",
        address: "Pune",
        isAdmin: false,
       },
   
]